# -*- coding: utf-8 -*-
"""En_tam_Machine_translation_infer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HnVq6XoY_-u8_rM7w7vgEkHhSFMi7D1-
"""

from google.colab import drive
drive.mount('/content/drive')
!pip install bunch
!pip install profanity_check
!pip install transformers
!pip install tensor2tensor

!nvidia-smi

import os
if not os.path.exists('Neural-Machine-Translation-English-Tamil-model'):
  !git clone https://github.com/praveenjune17/Neural-Machine-Translation-English-Tamil-model
  !unzip Neural-Machine-Translation-English-Tamil-model/tfds_patch_scripts/Transformer_en_tam_2.zip

try:
  import shutil
  shutil.rmtree('/content/Summarize_or_translate_using_transformers')
except:
  pass
!git clone https://github.com/praveenjune17/Summarize_or_translate_using_transformers

#set the path to the where tfds is installed
path = '/usr/local/lib/python3.6/dist-packages/tensorflow_datasets'
shutil.copy('../content/Transformer_en_tam_2/__init__.py', os.path.join(path, 'translate/__init__.py'))
shutil.copy('../content/Transformer_en_tam_2/en_tam_parallel_text.py', os.path.join(path, 'translate/en_tam_parallel_text.py'))
shutil.copy('../content/Transformer_en_tam_2/en_tam_parallel_text_test.py', os.path.join(path, 'translate/en_tam_parallel_text_test.py'))
shutil.copy('../content/Transformer_en_tam_2/en_tam_parallel_text.txt', os.path.join(path, 'url_checksums/en_tam_parallel_text.txt'))
#shutil.copy('../content/transformers-with-2stagedecoders/scripts/configuration_colab.py', '../content/transformers-with-2stagedecoders/scripts/configuration.py')
#shutil.copy('../content/Summarize_or_translate_using_transformers/scripts/train_temp_colab.py', '../content/Summarize_or_translate_using_transformers/scripts/train_temp.py')

!python /content/Summarize_or_translate_using_transformers/inference_scripts/translate.py

